Create Tdarr_Plugin_00td_action_transcode.js
HaveAGitGat/Tdarr_Plugins pull request #423
Opened 2023-06-26 17:04 UTC by HaveAGitGat

2023-06-26 17:25 UTC, supersnellehenk requested changes

2023-06-26 17:25 UTC, supersnellehenk commented on Community/Tdarr_Plugin_00td_action_transcode.js
> +    },
Might just wanna make it a dropdown instead of allowing untested containers?

2023-06-26 17:25 UTC, supersnellehenk commented on Community/Tdarr_Plugin_00td_action_transcode.js
> +  let duration = '';
Initialized as an empty string but assigned as a number

2023-06-26 17:25 UTC, supersnellehenk commented on Community/Tdarr_Plugin_00td_action_transcode.js
> +  if (inputs.container === '') {
Once it's a dropdown, can't be empty :)

2023-06-27 04:50 UTC, HaveAGitGat commented on Community/Tdarr_Plugin_00td_action_transcode.js
> +    + `-spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 ${extraArguments}`;
-map 0 should copy all streams but have added `-c copy` just to be explicit

2023-06-27 07:23 UTC, supersnellehenk commented on Community/Tdarr_Plugin_00td_action_transcode.js
> +    + `-spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 ${extraArguments}`;
It only maps streams, then it's up to ffmpeg defaults to decide what it'll do with them if you don't specify it has to copy the codec for those mapped streams.

2023-08-08 06:25 UTC, merged